version: '3.7'

services:

  flask-api:
    build: ./Flask
    image: localhost:5000/flask_api_service
    command: gunicorn --workers=2 --threads=2 --bind 0.0.0.0:8000 app
    volumes:
      - ./Flask/:/app/
    ports:
      - 80
    env_file:
      - ./Env/.env-dev

  nginx:
    build: ./nginx
    image: localhost:5000/nginx_service
    ports:
      - 6000:80
    depends_on:
      - flask-api